import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import GlobalCreateProjectModal from '@/components/modals/GlobalCreateProjectModal';

import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kitchen Voyager',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-background text-foreground`}>
        <Providers>
          {children}
          <GlobalCreateProjectModal />
        </Providers>
      </body>
    </html>
  )
}
